repos:
  - repo: https://github.com/bridgecrewio/checkov
    rev: v3.2.493
    hooks:
      - id: checkov
        name: checkov (terraform + r√®gles custom)
        args:
          - --framework
          - terraform
          - --download-external-modules
          - "false"
          - --external-checks-dir
          - custom_checks
          - --evaluate-variables
